import { useEffect, useState } from 'react';
import { FileText, Printer, RefreshCw } from 'lucide-react';
import { networkService } from '../services/api';
import { useAuth } from '../contexts/AuthContext';
import { useNotification } from '../contexts/NotificationContext';
import { isAdmin, roleLabel } from '../utils/roles';
import { RangePicker } from '../components/Charts';

function Kpi({ label, value, hint }) {
  return (
    <div className="bg-white rounded-xl border border-gray-200 p-4 shadow-sm print:shadow-none">
      <p className="m-0 text-xs uppercase tracking-wide text-gray-500">{label}</p>
      <p className="m-0 mt-1 text-2xl font-bold text-gray-900">{value}</p>
      {hint ? <p className="m-0 mt-1 text-xs text-gray-500">{hint}</p> : null}
    </div>
  );
}

function Section({ title, children }) {
  return (
    <section className="bg-white rounded-xl border border-gray-200 p-5 shadow-sm print:shadow-none print:break-inside-avoid">
      <h2 className="m-0 text-base font-bold text-[#1e3c72] border-b border-gray-100 pb-2 mb-4">{title}</h2>
      {children}
    </section>
  );
}

function fmtMs(v) {
  if (v == null || Number.isNaN(Number(v))) return '—';
  return `${Math.round(Number(v))} ms`;
}

function fmtDate(v) {
  if (!v) return '—';
  try {
    return new Date(v).toLocaleString();
  } catch {
    return String(v);
  }
}

export default function GeneralReportPage() {
  const { user } = useAuth();
  const { showError } = useNotification();
  const [data, setData] = useState(null);
  const [range, setRange] = useState('7d');
  const [loading, setLoading] = useState(true);

  const load = () => {
    setLoading(true);
    networkService
      .generalReport({ range })
      .then((res) => {
        if (res.success) setData(res.data);
        else showError(res.message || 'Could not load general report');
      })
      .catch((e) => showError(e.response?.data?.message || 'Could not load general report'))
      .finally(() => setLoading(false));
  };

  useEffect(() => {
    if (!isAdmin(user?.role)) return;
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [range, user?.role]);

  if (!isAdmin(user?.role)) {
    return (
      <div className="rounded-xl border border-amber-200 bg-amber-50 px-4 py-6 text-amber-900">
        <h1 className="m-0 text-lg font-bold">General report</h1>
        <p className="m-0 mt-2 text-sm">Only the Administrator can open the general system report.</p>
      </div>
    );
  }

  const kpis = data?.kpis || {};

  return (
    <div className="space-y-5">
      <div className="flex items-start justify-between gap-4 flex-wrap print:hidden">
        <div>
          <h1 className="m-0 text-xl font-bold text-gray-900 flex items-center gap-2">
            <FileText size={22} className="text-[#00628b]" />
            General report
          </h1>
          <p className="m-0 mt-1 text-sm text-gray-500 max-w-2xl">
            One-page management summary of services, failures, recoveries, users, and evaluation KPIs for screenshots and academic reporting.
          </p>
        </div>
        <div className="flex items-center gap-2 flex-wrap">
          <RangePicker value={range} onChange={setRange} />
          <button
            type="button"
            onClick={load}
            className="inline-flex items-center gap-2 rounded-lg border border-gray-300 bg-white px-3 py-2 text-sm font-medium text-gray-700 hover:bg-gray-50"
          >
            <RefreshCw size={16} /> Refresh
          </button>
          <button
            type="button"
            onClick={() => window.print()}
            className="inline-flex items-center gap-2 rounded-lg bg-[#00628b] px-3 py-2 text-sm font-medium text-white hover:bg-[#004e6e]"
          >
            <Printer size={16} /> Print / Save PDF
          </button>
        </div>
      </div>

      {loading && !data ? (
        <div className="flex justify-center py-16">
          <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-[#00628b]" />
        </div>
      ) : data ? (
        <div id="general-report-print" className="space-y-5">
          <Section title="Report header">
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3 text-sm">
              <p className="m-0"><span className="text-gray-500">Title:</span> <strong>{data.title}</strong></p>
              <p className="m-0"><span className="text-gray-500">Institution:</span> <strong>{data.institution}</strong></p>
              <p className="m-0"><span className="text-gray-500">Period:</span> <strong>{data.range?.label}</strong></p>
              <p className="m-0"><span className="text-gray-500">Generated:</span> <strong>{fmtDate(data.generatedAt)}</strong></p>
              <p className="m-0"><span className="text-gray-500">Generated by:</span> <strong>{data.generatedBy?.names || '—'}</strong> ({roleLabel(data.generatedBy?.role)})</p>
              <p className="m-0"><span className="text-gray-500">From → To:</span> <strong>{fmtDate(data.range?.since)} → {fmtDate(data.range?.until)}</strong></p>
            </div>
            <p className="m-0 mt-4 text-sm leading-relaxed text-gray-700 bg-[#f3f9fc] border border-[#cfe3ee] rounded-lg px-4 py-3">
              {data.narrative}
            </p>
          </Section>

          <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
            <Kpi label="Services" value={kpis.totalServices ?? 0} hint={`${kpis.monitoredServices ?? 0} monitored`} />
            <Kpi label="Problems (period)" value={kpis.failuresInRange ?? 0} hint={`${kpis.openFailures ?? 0} still open (all-time)`} />
            <Kpi label="Automatic fixes" value={kpis.recoveriesInRange ?? 0} hint={`${kpis.recoverySuccessRate ?? 0}% success`} />
            <Kpi label="Avg detect / fix" value={`${kpis.avgDetectionMs ?? 0} / ${kpis.avgRecoveryMs ?? 0} ms`} hint="Lower is better" />
            <Kpi label="Health OK rate" value={`${kpis.healthSuccessRate ?? 0}%`} hint={`${kpis.healthChecksInRange ?? 0} checks`} />
            <Kpi label="False positives" value={`${kpis.falsePositiveRate ?? 0}%`} hint="Glitch / non-outage rate" />
            <Kpi label="Restart / Failover" value={`${kpis.restartActions ?? 0} / ${kpis.failoverActions ?? 0}`} hint="Recovery action mix" />
            <Kpi label="Users" value={kpis.totalUsers ?? 0} hint={`${kpis.activeUsers ?? 0} active`} />
          </div>

          <Section title="Current service status">
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead>
                  <tr className="text-left text-gray-500 border-b">
                    <th className="py-2 pr-3">Service</th>
                    <th className="py-2 pr-3">Role</th>
                    <th className="py-2 pr-3">Status</th>
                    <th className="py-2 pr-3">Policy</th>
                    <th className="py-2 pr-3">Failures</th>
                    <th className="py-2 pr-3">Recoveries</th>
                    <th className="py-2 pr-3">Success %</th>
                    <th className="py-2 pr-3">Uptime %</th>
                    <th className="py-2">Avg latency</th>
                  </tr>
                </thead>
                <tbody>
                  {(data.perNode || []).map((n) => (
                    <tr key={n.id || n.key} className="border-b border-gray-50">
                      <td className="py-2 pr-3 font-medium text-gray-900">{n.name}</td>
                      <td className="py-2 pr-3 capitalize">{n.role}</td>
                      <td className="py-2 pr-3">{n.status}</td>
                      <td className="py-2 pr-3">{n.recoveryPolicy}</td>
                      <td className="py-2 pr-3">{n.failures}</td>
                      <td className="py-2 pr-3">{n.recoveries}</td>
                      <td className="py-2 pr-3">{n.recoverySuccessRate ?? '—'}{n.recoverySuccessRate != null ? '%' : ''}</td>
                      <td className="py-2 pr-3">{n.uptimePercent ?? '—'}{n.uptimePercent != null ? '%' : ''}</td>
                      <td className="py-2">{fmtMs(n.avgLatencyMs)}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Section>

          <Section title="Scenario summary (S1–S8)">
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead>
                  <tr className="text-left text-gray-500 border-b">
                    <th className="py-2 pr-3">Code</th>
                    <th className="py-2 pr-3">Description</th>
                    <th className="py-2 pr-3">Failures</th>
                    <th className="py-2 pr-3">Avg detect</th>
                    <th className="py-2 pr-3">Avg recover</th>
                    <th className="py-2">Success %</th>
                  </tr>
                </thead>
                <tbody>
                  {(data.scenarioSummary || []).length ? (
                    data.scenarioSummary.map((s) => (
                      <tr key={s.scenarioCode} className="border-b border-gray-50">
                        <td className="py-2 pr-3 font-semibold">{s.scenarioCode}</td>
                        <td className="py-2 pr-3">{s.label}</td>
                        <td className="py-2 pr-3">{s.failures}</td>
                        <td className="py-2 pr-3">{fmtMs(s.avgDetectionMs)}</td>
                        <td className="py-2 pr-3">{fmtMs(s.avgRecoveryMs)}</td>
                        <td className="py-2">{s.recoverySuccessRate != null ? `${s.recoverySuccessRate}%` : '—'}</td>
                      </tr>
                    ))
                  ) : (
                    <tr>
                      <td colSpan={6} className="py-4 text-gray-500">No scenario events in this period.</td>
                    </tr>
                  )}
                </tbody>
              </table>
            </div>
          </Section>

          <div className="grid grid-cols-1 xl:grid-cols-2 gap-5">
            <Section title="Recent problems">
              <div className="overflow-x-auto">
                <table className="min-w-full text-sm">
                  <thead>
                    <tr className="text-left text-gray-500 border-b">
                      <th className="py-2 pr-3">When</th>
                      <th className="py-2 pr-3">Service</th>
                      <th className="py-2 pr-3">Type</th>
                      <th className="py-2">Scenario</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(data.recentFailures || []).map((f) => (
                      <tr key={f.id} className="border-b border-gray-50">
                        <td className="py-2 pr-3 whitespace-nowrap">{fmtDate(f.detectedAt)}</td>
                        <td className="py-2 pr-3">{f.service}</td>
                        <td className="py-2 pr-3">{f.failureType}</td>
                        <td className="py-2">{f.scenarioCode || '—'}</td>
                      </tr>
                    ))}
                    {!data.recentFailures?.length ? (
                      <tr><td colSpan={4} className="py-3 text-gray-500">No failures in this period.</td></tr>
                    ) : null}
                  </tbody>
                </table>
              </div>
            </Section>

            <Section title="Recent automatic fixes">
              <div className="overflow-x-auto">
                <table className="min-w-full text-sm">
                  <thead>
                    <tr className="text-left text-gray-500 border-b">
                      <th className="py-2 pr-3">When</th>
                      <th className="py-2 pr-3">Service</th>
                      <th className="py-2 pr-3">Action</th>
                      <th className="py-2">Result</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(data.recentRecoveries || []).map((r) => (
                      <tr key={r.id} className="border-b border-gray-50">
                        <td className="py-2 pr-3 whitespace-nowrap">{fmtDate(r.startedAt)}</td>
                        <td className="py-2 pr-3">{r.service}</td>
                        <td className="py-2 pr-3">{r.actionType}{r.targetNodeKey ? ` → ${r.targetNodeKey}` : ''}</td>
                        <td className="py-2">{r.success ? `OK (${fmtMs(r.durationMs)})` : 'Failed'}</td>
                      </tr>
                    ))}
                    {!data.recentRecoveries?.length ? (
                      <tr><td colSpan={4} className="py-3 text-gray-500">No recoveries in this period.</td></tr>
                    ) : null}
                  </tbody>
                </table>
              </div>
            </Section>
          </div>

          <Section title="People & roles summary">
            <p className="m-0 mb-3 text-sm text-gray-600">
              Role counts:{' '}
              {Object.entries(data.roleCounts || {})
                .map(([role, count]) => `${roleLabel(role)} (${count})`)
                .join(' · ') || '—'}
            </p>
            <div className="overflow-x-auto">
              <table className="min-w-full text-sm">
                <thead>
                  <tr className="text-left text-gray-500 border-b">
                    <th className="py-2 pr-3">Name</th>
                    <th className="py-2 pr-3">Email</th>
                    <th className="py-2 pr-3">Role</th>
                    <th className="py-2">Active</th>
                  </tr>
                </thead>
                <tbody>
                  {(data.users || []).map((u) => (
                    <tr key={u.email} className="border-b border-gray-50">
                      <td className="py-2 pr-3">{u.names}</td>
                      <td className="py-2 pr-3">{u.email}</td>
                      <td className="py-2 pr-3">{roleLabel(u.role)}</td>
                      <td className="py-2">{u.active ? 'Yes' : 'No'}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </Section>

          <Section title="Monitoring settings">
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-sm">
              {Object.entries(data.settings || {}).map(([key, value]) => (
                <p key={key} className="m-0 rounded-lg bg-gray-50 px-3 py-2">
                  <span className="text-gray-500">{key}:</span> <strong>{String(value)}</strong>
                </p>
              ))}
              {!Object.keys(data.settings || {}).length ? (
                <p className="m-0 text-gray-500">No settings found.</p>
              ) : null}
            </div>
          </Section>
        </div>
      ) : (
        <p className="text-sm text-gray-500">No report data yet.</p>
      )}
    </div>
  );
}
